[package]
name = "b32768"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base32768 = { git = "https://github.com/Dreae/base32768-rs" } 
